Move AWS scale-out logic into provider file.

diff --git a/autoscaling/share/autoscaler b/autoscaling/share/autoscaler
--- a/autoscaling/share/autoscaler
+++ b/autoscaling/share/autoscaler
@@ -39,63 +39,7 @@ RUBY
   done
 }
 
-_collate_group_dimensions() {
-  local dims groups g
 
-  groups=()
-  _gather_groups() {
-    while [ "$1" != "--" ]; do shift; done
-    groups+=($(member_find_tag "aws_group" "$5"))
-  }
-  member_each _gather_groups
-  groups=($(printf "%s\n" "${groups[@]}" | sort -u | tr '\n' ' '))
-  log "[autoscaler:groups] Found groups: ${groups[*]}"
-
-  dims=()
-  for g in "${groups[@]}"; do
-    dims+=("$("${cw_ROOT}"/opt/jo/bin/jo Name=AutoScalingGroupName Value=${g})")
-  done
-  if [ "${#dims}" -gt 0 ]; then
-    "${cw_ROOT}"/opt/jo/bin/jo -a "${dims[@]}"
-  fi
-}
-
-_cores_for_group() {
-  local group_cores groups_cores g
-  group="$1"
-
-  groups_cores=()
-  _gather_group_cores() {
-    local group
-    while [ "$1" != "--" ]; do shift; done
-    group=$(member_find_tag "aws_group" "$5")
-    if [ "${group}" ]; then
-      groups_cores+=(${group}:$(member_find_tag "aws_group_cores" "$5"))
-    fi
-  }
-  member_each _gather_group_cores
-  groups_cores=($(printf "%s\n" "${groups_cores[@]}" | sort -u | tr '\n' ' '))
-  log "[autoscaler:cores_for_group] Found cores for groups: ${groups_cores[*]}"
-
-  if [ ${#group_cores[@]} -gt 1 -a -n "${group}" ]; then
-    log "[autoscaler:cores_for_group] Looking for group: ${group}"
-    for g in "${groups_cores[@]}"; do
-      if [[ $g == ${group}:* ]]; then
-        group_cores=$(echo "${g}" | cut -f2 -d":")
-        log "[autoscaler:cores_for_group] Found group '${group}' has cores: ${group_cores}"
-      fi
-    done
-  else
-    group_cores=$(echo "${groups_cores[0]}" | cut -f2 -d":")
-    log "[autoscaler:cores_for_group] Selecting first group '${groups_cores[0]}' with cores: ${group_cores}"
-  fi
-
-  if [ "${group_cores}" ]; then
-    echo "${group_cores}"
-  else
-    return 1
-  fi
-}
 
 _shoot_node() {
   local aws_exit_code node instanceid group
@@ -115,59 +59,7 @@ _shoot_node() {
   return ${aws_exit_code}
 }
 
-_set_job_metrics() {
-  # for all known scaling groups, set job metrics
-  local dims tmpfile scheduler cores_per_node job_total_var job_total
-  local job_queue_var job_queue job_run_var job_run
-  local cores_req_var cores_req nodes_req_var nodes_req
 
-  dims="$(_collate_group_dimensions)"
-  tmpfile="$(mktemp /tmp/autoscaler.XXXXXXXX)"
-  cores_per_node="$(_cores_for_group)"
-
-  for scheduler in "${_SCHEDULERS[@]}"; do
-    log "[autoscaler:metrics] Retrieving job state data for scheduler: ${scheduler}"
-    ${scheduler}_parse_job_states "${tmpfile}" "${cores_per_node}"
-    cat "${tmpfile}" | _log_blob "metrics"
-    . "${tmpfile}"
-    job_total_var="${scheduler}_job_total"
-    job_total=$((${job_total:-0}+${!job_total_var:-0}))
-    job_run_var="${scheduler}_job_run"
-    job_run=$((${job_run:-0}+${!job_run_var:-0}))
-    job_queue_var="${scheduler}_job_queue"
-    job_queue=$((${job_queue:-0}+${!job_queue_var:-0}))
-    cores_req_var="${scheduler}_cores_req"
-    cores_req=$((${cores_req:-0}+${!cores_req_var:-0}))
-    nodes_req_var="${scheduler}_nodes_req"
-    nodes_req=$((${nodes_req:-0}+${!nodes_req_var:-0}))
-  done
-
-  metrics=()
-  metrics+=($("${_JO}" MetricName=JobTotal Value=${job_total:-0} Unit=Count "Dimensions=${dims}"))
-  metrics+=($("${_JO}" MetricName=JobRun Value=${job_run:-0} Unit=Count "Dimensions=${dims}"))
-  metrics+=($("${_JO}" MetricName=JobQueue Value=${job_queue:-0} Unit=Count "Dimensions=${dims}"))
-  metrics+=($("${_JO}" MetricName=CoresReq Value=${cores_req:-0} Unit=Count "Dimensions=${dims}"))
-  metrics+=($("${_JO}" MetricName=NodesReq Value=${nodes_req:-0} Unit=Count "Dimensions=${dims}"))
-  "${_JO}" -a "${metrics[@]}" > "${tmpfile}"
-
-  # Send: JobTotal, JobRun, JobPending, CoresRequired, NodesRequired
-  log "[autoscaler:metrics] Sending metric data to cloudwatch"
-  cat "${tmpfile}" | _log_blob "metrics"
-
-  result=$("${_AWS}" --region "${cw_INSTANCE_aws_region}" \
-  cloudwatch put-metric-data \
-  --namespace "ALCES-SCHEDULING" \
-  --metric-data file://${tmpfile} 2>&1)
-  if echo "${result}" | grep -q AccessDenied; then
-    log "[autoscaler:metrics:aws] Access denied for PutMetricData; disabling."
-    mkdir -p "${cw_ROOT}"/var/lib/db/autoscaler
-    echo "disabled" > "${cw_ROOT}"/var/lib/db/autoscaler/disable-set_job_metrics
-  else
-    echo "${result}" | _log_blob "metrics:aws"
-  fi
-
-  rm -f "${tmpfile}"
-}
 
 _empty_nodes() {
   local scheduler empty_nodes
@@ -254,19 +146,29 @@ _setup_schedulers() {
   log "[autoscaler:setup_schedulers] Found autoscaling-capable scheduler(s): ${_SCHEDULERS[*]}"
 }
 
-_scale_out() {
-  if [ ! -f "${cw_ROOT}"/var/lib/db/autoscaler/disable-set_job_metrics ]; then
-    log "[autoscaler] Performing job metric scan"
-    _set_job_metrics
+_setup_autoscaling() {
+  local autoscaling_provider_file
+
+  echo "Preconfigured autoscaling type is ${cw_INSTANCE_autoscaling}"
+  autoscaling_provider_file="${cw_HANDLER_PLUGINDIR}/autoscaling/share/providers/${cw_INSTANCE_autoscaling}"
+
+  if [ -f "$autoscaling_provider_file" ]; then
+    . "$autoscaling_provider_file"
   else
-    log "[autoscaler] Skipping metric scan (currently disabled)"
+    echo "Provider file ${autoscaling_provider_file} not found, cannot configure autoscaling."
+    exit 1
   fi
 }
 
+_scale_out() {
+  ${cw_INSTANCE_autoscaling}-scale-out
+}
+
 main() {
-  if files_load_config --optional instance-aws config/cluster; then
-    if [ "${cw_INSTANCE_aws_autoscaling}" == "enabled" ]; then
+  if files_load_config instance config/cluster; then
+    if [ "${cw_INSTANCE_autoscaling}" != "disabled" ]; then
       _setup_schedulers
+      _setup_autoscaling
       _scale_out
       _scale_in
     else
@@ -289,5 +191,7 @@ _JO="${cw_ROOT}"/opt/jo/bin/jo
 _AWS="${cw_ROOT}"/opt/aws/bin/aws
 
 log_set_default "/var/log/clusterware/autoscaler.log"
+
+files_load_config instance config/cluster
 
 main "$@"
