Add more logging to customizer config retrieval.

diff --git a/cluster-customizer/initialize b/cluster-customizer/initialize
--- a/cluster-customizer/initialize
+++ b/cluster-customizer/initialize
@@ -133,18 +133,21 @@ _load_master_list() {
     sleep 10
   done
 
-  master_ip=$(grep -Po "(?<=master: )[0-9\.]*" ${cw_ROOT}/etc/config.yml)
+  if [ -f "${cw_ROOT}/etc/config.yml" ]; then
 
-  if [[ "${master_ip}" != "" ]]; then
+    master_ip=$(grep -Po "(?<=master: )[0-9\.]*" ${cw_ROOT}/etc/config.yml)
 
-    tmpfile="$(mktemp /tmp/cluster-customizer.XXXXXXXX)"
+    if [[ "${master_ip}" != "" ]]; then
 
-    mkdir -p "${cw_ROOT}/etc/cluster-customizer"
+      tmpfile="$(mktemp /tmp/cluster-customizer.XXXXXXXX)"
 
-    curl -Lsf -o "${cw_ROOT}/etc/cluster-customizer/config.yml" "http://${master_ip}/customizer/config.yml"
+      mkdir -p "${cw_ROOT}/etc/cluster-customizer"
+      echo "Retrieving customizer configuration from http://${master_ip}/customizer/config.yml"
 
-    if [ $? == 0 ]; then
-      ruby_run <<RUBY > "${tmpfile}"
+      curl -Lsf -o "${cw_ROOT}/etc/cluster-customizer/config.yml" "http://${master_ip}/customizer/config.yml"
+
+      if [ $? == 0 ]; then
+        ruby_run <<RUBY > "${tmpfile}"
 require 'yaml'
 master_list = YAML.load_file("${cw_ROOT}/etc/cluster-customizer/config.yml")
 
@@ -153,11 +156,16 @@ if master_list.key? "profiles"
 end
 
 RUBY
-      source "${tmpfile}"
-      rm "${tmpfile}"
+        source "${tmpfile}"
+        rm "${tmpfile}"
+      else
+        echo "Retrieving customizer configuration failed."
+      fi
+    else
+      echo "No master node IP specified, not loading customizer configuration from master."
     fi
   else
-    echo "No master node IP specified, not loading customizer configuration from master."
+    echo "${cw_ROOT}/etc/config.yml does not exist, can't load customizer configuration from master."
   fi
 }
 
