Updates to initial handlers.

diff --git a/clusterable/configure b/clusterable/configure
--- a/clusterable/configure
+++ b/clusterable/configure
@@ -8,8 +8,11 @@ setup() {
             break
         fi
     done
-    export cw_ROOT=${cw_ROOT:-/opt/clusterware}
-    source ${cw_ROOT}/lib/functions/core.functions.sh
+    if [ -z "${cw_ROOT}" ]; then
+        echo "$0: unable to locate clusterware configuration"
+        exit 1
+    fi
+    kernel_load
 }
 
 main() {
@@ -42,12 +45,15 @@ tags = config['tags'] || {}
 h = { tags: tags.merge({ role: config['role'] }) }
 write_file('serf/tags.json', h.to_json)
 
-instance_vars = []
-instance_vars << %(cw_NODE_role="#{config['role']}")
-instance_vars << %(cw_CLUSTER_uuid="#{config['uuid']}")
-instance_vars << %(cw_CLUSTER_quorum="#{config['quorum']}")
+cluster_vars = []
+cluster_vars << %(cw_CLUSTER_uuid="#{config['uuid']}")
+cluster_vars << %(cw_CLUSTER_quorum="#{config['quorum'] || 1}")
+cluster_vars << %(cw_CLUSTER_service_url="#{config['service_url']}")
+write_file('cluster.vars.sh', cluster_vars.join("\n"))
+
+instance_vars << %(cw_INSTANCE_role="#{config['role']}")
 config['tags'].each do |k,v|
-  instance_vars << %(cw_NODE_tag_#{k.upcase}="#{v}")
+  instance_vars << %(cw_INSTANCE_tag_#{k.upcase}="#{v}")
 end
 write_file('instance.vars.sh', instance_vars.join("\n"))
 RUBY
diff --git a/clusterable/member-join b/clusterable/member-join
--- a/clusterable/member-join
+++ b/clusterable/member-join
@@ -8,20 +8,23 @@ setup() {
             break
         fi
     done
-    export cw_ROOT=${cw_ROOT:-/opt/clusterware}
-    source ${cw_ROOT}/lib/functions/core.functions.sh
+    if [ -z "${cw_ROOT}" ]; then
+        echo "$0: unable to locate clusterware configuration"
+        exit 1
+    fi
+    kernel_load
 }
 
 main() {
     member_register
     if [ "$(member_count)" -ge "$(member_quorum)" ]; then
-        hook_run cluster-quorate
+        handler_run_hook cluster-quorate
     fi
 }
 
 setup
 
 require member
-require hook
+require handler
 
 main "$@"
diff --git a/flight/session-screenshot b/flight/session-screenshot
--- a/flight/session-screenshot
+++ b/flight/session-screenshot
@@ -1,3 +1,34 @@
 #!/bin/bash
-SESSIONID="$1"
+setup() {
+    local a xdg_config
+    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
+    for a in "${xdg_config[@]}"; do
+        if [ -e "${a}"/clusterware/config.vars.sh ]; then
+            source "${a}"/clusterware/config.vars.sh
+            break
+        fi
+    done
+    if [ -z "${cw_ROOT}" ]; then
+        echo "$0: unable to locate clusterware configuration"
+        exit 1
+    fi
+    kernel_load
+}
+
+main() {
+    local sessionid
+    local -A vnc
+
+    sessionid="$1"
+    if sessiondir=$(vnc_find_sessiondir "${sessionid}"); then
+        sessionid=$(basename "$sessiondir")
+        webapi_delete "${cw_CLUSTER_service_url}"/sessions/${sessionid}
+    fi
+}
+
+setup
+require vnc
+require webapi
+main "$@"
+
 tee | >(base64 -d > /tmp/${SESSIONID}.$(date "+%Y-%m-%d-%H%M%S").png)
diff --git a/flight/session-start b/flight/session-start
--- a/flight/session-start
+++ b/flight/session-start
@@ -1,2 +1,54 @@
 #!/bin/bash
-echo "Session started"
+setup() {
+    local a xdg_config
+    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
+    for a in "${xdg_config[@]}"; do
+        if [ -e "${a}"/clusterware/config.vars.sh ]; then
+            source "${a}"/clusterware/config.vars.sh
+            break
+        fi
+    done
+    if [ -z "${cw_ROOT}" ]; then
+        echo "$0: unable to locate clusterware configuration"
+        exit 1
+    fi
+    kernel_load
+}
+
+main() {
+    local sessionid
+    local -A vnc
+
+    sessionid="$1"
+    if sessiondir=$(vnc_find_sessiondir "${sessionid}"); then
+        sessionid=$(basename "$sessiondir")
+        . "${sessiondir}"/metadata.vars.sh
+        . "${cw_ROOT}"/etc/config/cluster.vars.sh
+        cat <<JSON | webapi_post "${cw_CLUSTER_service_url}"/sessions
+{
+    "data": {
+        "type": "session",
+        "id": "${session_id}},
+        "attributes": {
+            "user": "${USER}",
+            "host": "${vnc[ADDRESS]}",
+            "port": "${vnc[PORT]}",
+            "display": "${vnc[DISPLAY]}",
+            "password": "${vnc[PASSWORD]}",
+            "websocket": "${vnc[WEBSOCKET]}"
+        },
+        "relationships: {
+            "cluster": {
+                 "data": {"type": "cluster", "id": "${cw_CLUSTER_uuid}"}
+            }
+        }
+    }
+}
+JSON
+    fi
+}
+
+setup
+require vnc
+require webapi
+main "$@"
diff --git a/taskable/configure b/taskable/configure
--- a/taskable/configure
+++ b/taskable/configure
@@ -1,19 +1,34 @@
 #!/bin/bash
-alces_ROOT="/opt/clusterware"
+setup() {
+    local a xdg_config
+    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
+    for a in "${xdg_config[@]}"; do
+        if [ -e "${a}"/clusterware/config.vars.sh ]; then
+            source "${a}"/clusterware/config.vars.sh
+            break
+        fi
+    done
+    if [ -z "${cw_ROOT}" ]; then
+        echo "$0: unable to locate clusterware configuration"
+        exit 1
+    fi
+    kernel_load
+}
 
-# Bail out if we're already configured (this is a reboot)
-if [ -d "${alces_ROOT}/etc/config/instance" ]; then
-  exit 0
-fi
+main() {
+    # Bail out if we're already configured (this is a reboot)
+    if [ -d "${cw_ROOT}/etc/config/task" ]; then
+        exit 0
+    fi
 
-# Bail out if we can't locate the config file
-if [ ! -f "${alces_ROOT}/etc/config.yml" ]; then
-  exit 1
-fi
+    # Bail out if we can't locate the config file
+    if [ ! -f "${cw_ROOT}/etc/config.yml" ]; then
+        exit 1
+    fi
 
-# Parse YAML file into something useful
-mkdir -p "${alces_ROOT}/etc/config/instance"
-/opt/clusterware/opt/ruby/bin/ruby -se 'eval ARGF.read' <<RUBY
+    # Parse YAML file into something useful
+    mkdir -p "${cw_ROOT}/etc/config/task"
+    ruby_run <<RUBY
 require 'yaml'
 
 def groupadd_cmd(name, gid = nil)
@@ -44,16 +59,16 @@ SSH
 end
 
 def write_file(name, content)
-  File.write("${alces_ROOT}/etc/config/instance/#{name}",content)
+  File.write("${cw_ROOT}/etc/config/tak/#{name}",content)
 end
 
-config = YAML.load_file('${alces_ROOT}/etc/config.yml')['instance']
+config = YAML.load_file('${cw_ROOT}/etc/config.yml')['instance']
 
 task_vars = []
 config['control']['params'].each do |k,v|
-  task_vars << %(#{k.upcase}="#{v}")
+  task_vars << %(cw_TASK_param_#{k.upcase}="#{v}")
 end
-task_vars << %(RUNUSER="#{config['users'].first['username']}")
+task_vars << %(cw_TASK_RUNUSER="#{config['users'].first['username']}")
 write_file('task.vars.sh', task_vars.join("\n"))
 
 user_cmds = []
@@ -77,5 +92,12 @@ config['control']['scripts'].each do |name, content|
 end
 RUBY
 
-# Create user(s)
-source "${alces_ROOT}/etc/config/instance/create-users.sh"
+    # Create user(s)
+    source "${cw_ROOT}/etc/config/task/create-users.sh"
+}
+
+setup
+
+require ruby
+
+main "$@"
diff --git a/taskable/preamble b/taskable/preamble
--- a/taskable/preamble
+++ b/taskable/preamble
@@ -1,6 +1,24 @@
 #!/bin/bash
-alces_ROOT="/opt/clusterware"
+setup() {
+    local a xdg_config
+    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
+    for a in "${xdg_config[@]}"; do
+        if [ -e "${a}"/clusterware/config.vars.sh ]; then
+            source "${a}"/clusterware/config.vars.sh
+            break
+        fi
+    done
+    if [ -z "${cw_ROOT}" ]; then
+        echo "$0: unable to locate clusterware configuration"
+        exit 1
+    fi
+    kernel_load
+}
 
-if [ -f "${alces_ROOT}/etc/config/instance/preamble.sh" ]; then
-  /bin/bash "${alces_ROOT}/etc/config/instance/preamble.sh"
-fi
+main() {
+    process_sh "${cw_ROOT}/etc/config/instance/preamble.sh"
+}
+
+setup
+require process
+main "$@"
