Correct regex for checking if a node is already in genders file; add locking.  Refs #18.

diff --git a/cluster-sge/share/sge-add-node b/cluster-sge/share/sge-add-node
--- a/cluster-sge/share/sge-add-node
+++ b/cluster-sge/share/sge-add-node
@@ -6,6 +6,15 @@ module purge
 module use "${cw_ROOT}"/etc/modules
 module load services/gridscheduler
 
+_lock() {
+    mkdir -p "${cw_ROOT}"/var/lock
+    exec 9> "${cw_ROOT}"/var/lock/cluster-sge.lock && flock -w30 9
+}
+
+_unlock() {
+    exec 9>&-
+}
+
 if [ -f "${cw_ROOT}/etc/cluster-sge.rc" ]; then
     . "${cw_ROOT}/etc/cluster-sge.rc"
 fi
@@ -48,37 +57,48 @@ report_variables      NONE
 EOF
 qconf -Ae "${tmpfile}" || qconf -Me "${tmpfile}"
 
-set -o pipefail
-# Remove any existing record from all hostgroups
-for a in $(qconf -shgrpl); do
-    if qconf -shgrp ${a} | grep -q "${name}"; then
-        qconf -shgrp ${a} | sed -e "s/^\(.*\) ${name}\(.*\)/\1\2/g" \
-            -e "s/hostlist\s*$/hostlist NONE/g" > "${tmpfile}" && \
+if _lock; then
+    set -o pipefail
+    # Remove any existing record from all hostgroups
+    for a in $(qconf -shgrpl); do
+	if qconf -shgrp ${a} | grep -q "${name}"; then
+            qconf -shgrp ${a} | sed -e "s/^\(.*\) ${name}\(.*\)/\1\2/g" \
+				    -e "s/hostlist\s*$/hostlist NONE/g" > "${tmpfile}" && \
+		qconf -Mhgrp "${tmpfile}"
+	fi
+    done
+
+    # Add to allhosts group
+    qconf -shgrp @allhosts | sed -e "s/^hostlist NONE/hostlist /g" \
+				 -e "s/^hostlist \(.*\)/hostlist ${name} \1/g" > "${tmpfile}" && \
+	qconf -Mhgrp "${tmpfile}"
+
+    if [ $slots -gt 1 ]; then
+	# Add to slot-aware hostgroup
+	qconf -shgrp @${slots}slot | sed -e "s/^hostlist NONE/hostlist /g" \
+					 -e "s/^hostlist \(.*\)/hostlist ${name} \1/g" > "${tmpfile}" && \
             qconf -Mhgrp "${tmpfile}"
     fi
-done
 
-# Add to allhosts group
-qconf -shgrp @allhosts | sed -e "s/^hostlist NONE/hostlist /g" \
-    -e "s/^hostlist \(.*\)/hostlist ${name} \1/g" > "${tmpfile}" && \
-    qconf -Mhgrp "${tmpfile}"
+    # Workaround to make qmaster pay attention to hostgroup slots
+    qconf -sq byslot.q > "${tmpfile}" && \
+	qconf -Mq "${tmpfile}"
 
-if [ $slots -gt 1 ]; then
-    # Add to slot-aware hostgroup
-    qconf -shgrp @${slots}slot | sed -e "s/^hostlist NONE/hostlist /g" \
-        -e "s/^hostlist \(.*\)/hostlist ${name} \1/g" > "${tmpfile}" && \
-        qconf -Mhgrp "${tmpfile}"
+    _unlock
+    set +o pipefail
+else
+    echo "Locking failed; unable to update hostgroups files for ${short_name}"
 fi
 
-# Workaround to make qmaster pay attention to hostgroup slots
-qconf -sq byslot.q > "${tmpfile}" && \
-    qconf -Mq "${tmpfile}"
-
-set +o pipefail
 rm -f "${tmpfile}"
 
 if [ -f "${cw_ROOT}"/etc/genders ]; then
-    if ! grep -q "^${short_name}" "${cw_ROOT}"/etc/genders; then
-        echo "${short_name} nodes,compute,cluster,slave,all" >> "${cw_ROOT}"/etc/genders
+    if ! grep -q "^${short_name} " "${cw_ROOT}"/etc/genders; then
+	if _lock; then
+            echo "${short_name} nodes,compute,cluster,slave,all" >> "${cw_ROOT}"/etc/genders
+	    _unlock
+	else
+	    echo "Locking failed; unable to update genders file for ${short_name}"
+	fi
     fi
 fi
diff --git a/cluster-sge/share/sge-prune-node b/cluster-sge/share/sge-prune-node
--- a/cluster-sge/share/sge-prune-node
+++ b/cluster-sge/share/sge-prune-node
@@ -6,6 +6,15 @@ module purge
 module use "${cw_ROOT}"/etc/modules
 module load services/gridscheduler
 
+_lock() {
+    mkdir -p "${cw_ROOT}"/var/lock
+    exec 9> "${cw_ROOT}"/var/lock/cluster-sge.lock && flock -w30 9
+}
+
+_unlock() {
+    exec 9>&-
+}
+
 if [ -f "${cw_ROOT}/etc/cluster-sge.rc" ]; then
     . "${cw_ROOT}/etc/cluster-sge.rc"
 fi
@@ -26,23 +35,32 @@ fi
 
 tmpfile="$(mktemp /tmp/sge-prune-node.XXXXXXXX)"
 
-set -o pipefail
-# Remove any existing record from all hostgroups
-for a in $(qconf -shgrpl); do
-    if qconf -shgrp ${a} | grep -q "${name}"; then
-        qconf -shgrp ${a} | sed -e "s/^\(.*\) ${name}\(.*\)/\1\2/g" \
-            -e "s/hostlist\s*$/hostlist NONE/g" > "${tmpfile}" && \
-            qconf -Mhgrp "${tmpfile}"
-    fi
-done
-set +o pipefail
+if _lock; then
+    set -o pipefail
+    # Remove any existing record from all hostgroups
+    for a in $(qconf -shgrpl); do
+	if qconf -shgrp ${a} | grep -q "${name}"; then
+            qconf -shgrp ${a} | sed -e "s/^\(.*\) ${name}\(.*\)/\1\2/g" \
+				    -e "s/hostlist\s*$/hostlist NONE/g" > "${tmpfile}" && \
+		qconf -Mhgrp "${tmpfile}"
+	fi
+    done
+    set +o pipefail
+else
+    echo "Locking failed; unable to prune ${short_name} from hostgroups files"
+fi
 
 qconf -de "${name}"
 
 if [ -f "${cw_ROOT}"/etc/genders ]; then
     if grep -q "^${short_name} " "${cw_ROOT}"/etc/genders; then
-	grep -v "^${short_name} " "${cw_ROOT}"/etc/genders > "${tmpfile}"
-	cat "${tmpfile}" > "${cw_ROOT}"/etc/genders
+	if _lock; then
+	    grep -v "^${short_name} " "${cw_ROOT}"/etc/genders > "${tmpfile}"
+	    cat "${tmpfile}" > "${cw_ROOT}"/etc/genders
+	    _unlock
+	else
+	    echo "Locking failed; unable to prunte ${short_name} from genders file"
+	fi
     fi
 fi
 
