Reworking cluster-nfs handler and hooks. Refs #16 and refs #14.

diff --git a/cluster-nfs/metadata.yml b/cluster-nfs/metadata.yml
--- a/cluster-nfs/metadata.yml
+++ b/cluster-nfs/metadata.yml
@@ -5,6 +5,16 @@ install:
   el7: |
     yum install -y -e0 nfs-utils
   _: |
+    require files
+    files_load_config clusterware
+    case "${cw_VERSION:-1.0.0}" in
+      1.[0123].*)
+          echo "This handler cannot be enabled as Alces Clusterware v${cw_VERSION} is too old."
+          echo "Please upgrade to Alces Clusterware v1.4.0 or higher."
+          exit 1
+          ;;
+    esac
+
     if [ ! -f "${cw_ROOT}"/etc/cluster-nfs.rc ]; then
         cat <<EOF >> "${cw_ROOT}"/etc/cluster-nfs.rc
     cw_CLUSTER_NFS_exports="/home"
