Update to use clusterware-specific sudoers configuration directory.

diff --git a/session-firewall/metadata.yml b/session-firewall/metadata.yml
--- a/session-firewall/metadata.yml
+++ b/session-firewall/metadata.yml
@@ -1,7 +1,7 @@
 ################################################################################
 ##
 ## Alces Clusterware - Handler metadata
-## Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
+## Copyright (C) 2015-2016 Stephen F. Norledge and Alces Software Ltd.
 ##
 ################################################################################
 ---
@@ -9,7 +9,24 @@ description: |
   Configure firewall to expose sessions.
 install:
   _: |
-    cat <<EOF > /etc/sudoers.d/clusterware-handler-session-firewall
+    require files
+    files_load_config clusterware
+    case "${cw_VERSION:-1.0.0}" in
+      1.[01234].*)
+          echo "This handler cannot be enabled as Alces Clusterware v${cw_VERSION} is too old."
+          echo "Please upgrade to Alces Clusterware v1.5.0 or higher."
+          exit 1
+          ;;
+    esac
+
+    cat <<EOF > "${cw_ROOT}"/etc/sudoers.d/clusterware-handler-session-firewall
+    ################################################################################
+    ##
+    ## Alces Clusterware - sudoers configuration file
+    ## Copyright (c) 2015-2016 Alces Software Ltd
+    ##
+    ################################################################################
     Defaults!${cw_ROOT}/etc/handlers/session-firewall/session-* !requiretty
     ALL ALL=(root) NOPASSWD:${cw_ROOT}/etc/handlers/session-firewall/session-*
     EOF
+    chmod 0400 "${cw_ROOT}"/etc/sudoers.d/clusterware-handler-session-firewall
